### ISSUE TITLE
Invariant Violation: img is a void element tag

### ISSUE THREAD

**Issue by ankit-casaone** [benjycui/jsonml-to-react-element#2]
I am getting **Unhandled rejection Invariant Violation: img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.** as error.

I think this is happening because the img tag is getting converted to `<img src="" alt>` instead of getting converted to `<img src="" alt />`. The absence of closing tag is making React throw this error is my guess.

Or is it possible that I am doing something wrong here?

Can you confirm whether img tag gets converted to `<img>` or `<img />` ?
Thanks!

**Comment by benjycui** [comment]
Just `rm -rf node_modules && npm i`

**Comment by dhilip1** [comment]
even after this getting the same error ,tried wrapping in a div also

<div>
                    <Logo />
                     <ImageLinkForm 
                          onInputChange={this.onInputChange} 
                          onButtonSubmit={this.onButtonSubmit}
                        />
                    <HelmetViolation imageUrl={this.state.input}/>
                    <h1> { this.state.route} </h1>

                 
                       <img id='img1' src="\vehicleNumber1.jpg" alt="test" style="float:left"> </img>
                    
                    
              </div>
