### ISSUE TITLE
BR is a void element

### ISSUE THREAD

**Issue by ankit-casaone** [benjycui/jsonml-to-react-element#4]
I am getting the following error
Unhandled rejection Invariant Violation: br is a void element tag and must neither have "children" nor use "dangerouslySetInnerHTML".
My JsonML is the following:

        [
            "H4",
            {
                "style": "line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"
            },
            [
                "BR"
            ]
        ]

Please help

**Comment by benjycui** [comment]
Just update to the latest version https://github.com/benjycui/jsonml-to-react-element/blob/master/src/utils.js#L41-L59
